[project]
name = "backend-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask-cors>=5.0.0",
    "flask>=3.0.3",
    "psycopg>=3.2.3",
    "ultralytics>=8.3.27",
]